[package]
name = "stupid_snake"
version = "0.1.0"
authors = ["Michael Allen <mallenjr42@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tflite = "0.9.6"
cpal = "0.13.4"